manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/AeternusCo/
  projects:
    - name: zmk-old
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
